pool:
  name: Azure Pipelines
  vmImage: windows-2019

trigger:
  - master

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: 10.x

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: npm run cy:verify
    displayName: 'Cypress Verify'

  - script: npm run cy:run:reporter
    displayName: "Run Cypress tests"

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/cypress-and-azure-devops-*.xml"