pool:
  name: Azure Pipelines
  vmImage: windows-2019

trigger:
  - master

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: 10.x

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npm run test
    displayName: 'Run Cypress tests'