name: 'Cypress E2E Testing'

trigger:
  - master

schedules:
  - cron: "0 6 * * *"
    displayName: Each morning at 6am
    branches:
      include:
        - dev

- script:
    npm install
    npm run build
    npm test
displayName: 'npm install and build'