pool:
  name: Azure Pipelines
  vmImage: windows-2019

trigger:
  - master

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: 10.x

  - script: "npm install"
    displayName: "npm Install"

  - script: "npm run cy:verify"
    displayName: "Cypress Verify"

  - script: "npm run cy:run:reporter"
    displayName: "Run Cypress tests"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: cypress-and-azure-devops Screenshots "
    inputs:
      PathtoPublish: cypress/screenshots
      ArtifactName: CypressAndAzureDevopsTestRunScreenshots
    condition: failed()

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: cypress-and-azure-devops Videos "
    inputs:
      PathtoPublish: cypress/videos
      ArtifactName: CypressAndAzureDevopsTestRunVideos
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/cypress-and-azure-devops-*.xml"