version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm run test
  nightly:
    triggers:
      - schedule:
          cron: "56 11 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          start: npm run test